name: Publish to NPM

on:
  release:
    types: [published]
  workflow_dispatch: # Allow manual triggering

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run linting
        run: npm run lint || true
        
      - name: Build package
        run: npm run build
        
      - name: Verify build output
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "Package.json contents:"
          cat package.json | head -20
          echo "Dist directory contents:"
          ls -la dist/ || echo "Dist directory not found"
        
      - name: Run tests (if available)
        run: npm test --if-present || echo "No tests found, continuing..."
        
      - name: Validate NPM Token
        run: |
          if [ -z "${{ secrets.NPM_TOKEN }}" ]; then
            echo "❌ NPM_TOKEN secret is not configured"
            echo "Please add NPM_TOKEN to your repository secrets"
            exit 1
          else
            echo "✅ NPM_TOKEN secret is configured"
            echo "Token length: ${#NPM_TOKEN}"
          fi
        
      - name: Publish to NPM
        run: |
          echo "Attempting to publish to NPM..."
          echo "Registry URL: $(npm config get registry)"
          echo "Token available: $([ -n "$NODE_AUTH_TOKEN" ] && echo "Yes" || echo "No")"
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - name: Success message
        run: |
          echo "🎉 Package published successfully to NPM!"
          echo "Package: react-theme-system"
          echo "Version: $(node -p "require('./package.json').version")"
